### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by Gurasshrimp** [NICK-FURY-6023/247-YouTube-Livestreaming#1]
I tried to replaced my stream url, but it says `live.sh: 1: cannot open (my url): No such file`
So i tried to use the original one, but it says that too.
I don't understand ffmpeg and node.js, what do I do?
![image](https://github.com/NICK-FURY-6023/247-YouTube-Livestreaming/assets/111885280/1cfc1fc7-aa78-412a-8f30-675dce41ad06)

**Comment by NICK-FURY-6023** [comment]
first you  need to add your audio file on there 

then chnage  your youtube stream key or you need to chnage  to your video then  change video file
